### ISSUE TITLE
Add support for subpaths exports

### ISSUE THREAD

**Issue by Comandeer** [Comandeer/rollup-lib-bundler#185]
See https://nodejs.org/api/packages.html#packages_subpath_exports

**Comment by chadhall2152** [comment]
> See [https://nodejs.org/api/packages.html#packages_subpath_exports](https://nodejs.org/api/packages.html#packages_subpath_exports)

**Comment by chadhall2152** [comment]
> See https://nodejs.org/api/packages.html#packages_subpath_exports
